### ISSUE TITLE
Error with SSL socket of APNS

### ISSUE THREAD

**Issue by tridc** [jleclanche/django-push-notifications#311]
I've got this problem recently with creating socket of APNS
[SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:600)

The related line in apns.py
sock = ssl.wrap_socket(sock, ssl_version=ssl.PROTOCOL_TLSv1, certfile=certfile, ca_certs=ca_certs)

Does anyone get this?

**Comment by Proper-Job** [comment]
@tridc Can you post the stack trace?

**Comment by tridc** [comment]
Here is the trace:

Traceback (most recent call last):
  File "/home/tridc/git/pushnotif/tasks.py", line 77, in send_push_notification
    apns_devices.send_message(message, env=apns_env)
  File "/home/tridc/git/push_notifications/models.py", line 91, in send_message
    r = apns_send_bulk_message(registration_ids=reg_ids, alert=message, application_id=app_id, **kwargs)
  File "/home/tridc/git/push_notifications/apns.py", line 247, in apns_send_bulk_message
    with closing(_apns_create_socket_to_push(application_id, env)) as socket:
  File "/home/tridc/git/push_notifications/apns.py", line 81, in _apns_create_socket_to_push
    return _apns_create_socket((SETTINGS["APNS_HOST_PROD"], SETTINGS["APNS_PORT"]), application_id)
  File "/home/tridc/git/push_notifications/apns.py", line 74, in _apns_create_socket
    sock.connect(address_tuple)
  File "/usr/lib/python3.5/ssl.py", line 1019, in connect
    self._real_connect(addr, False)
  File "/usr/lib/python3.5/ssl.py", line 1010, in _real_connect
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:645)

A few times I tested push works properly. Does it seems to be APNS server's problem?

**Comment by Proper-Job** [comment]
@tridc Sorry, I'm drawing a blank here, too.  I thought it might have something to do with gunicorn and gevent monkey patching the SSLSocket implementation.  But it doesn't look like it.

**Comment by tridc** [comment]
I found out the reason, it's my certificate. Thanks for your comment.

**Comment by FlavioAlexander** [comment]
@tridc I am running into the same issue. What steps did you take to fix this problem? Would a new certificate fix it? Not really familiar with the whole process, any insight would be helpful 

Best,

Flavio

**Comment by tridc** [comment]
@FlavioAlexander it's only because my certificate is invalid and rejected by APN server.
