### ISSUE TITLE
Cannot use 'pip install git+<repo url>'

### ISSUE THREAD

**Issue by Malthael** [jleclanche/django-push-notifications#372]
I'm using `1.4.1` now, but I need to upgrade to newer version due to the usage of customizing `USER_MODEL`. (#281 says)

This is the messages I got when executed `sudo pip3.5 install git+https://github.com/jleclanche/django-push-notifications.git`:
```
Collecting git+https://github.com/jleclanche/django-push-notifications.git
  Cloning https://github.com/jleclanche/django-push-notifications.git to /tmp/pip-a0_20ck6-build
Installing collected packages: UNKNOWN
  Running setup.py install for UNKNOWN
Successfully installed UNKNOWN-0.0.0
```
And `python3.5 manage.py runserver` gives me:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 3
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 3
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 85, in popul
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'push_notifications'
```
Here is my settings about `django-push-notifications` in `settings.py`:
```
PUSH_NOTIFICATIONS_SETTINGS = {
    'GCM_API_KEY': '[your api key]',
    'APNS_CERTIFICATE': '/path/to/your/certificate.pem',
    'USER_MODEL': 'core.models.User',
}
```
Is there something I missed? Thanks a lot!

**Comment by jleclanche** [comment]
Try `pip install --upgrade setuptools` first.

**Comment by Malthael** [comment]
It works!

However, when I try to migrate `push_notifications` it gives me:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/utils.py", line 14, in make_model_tuple
    app_label, model_name = model.split(".")
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/site-packages/push_notifications/models.py", line 68, in <module>
    class GCMDevice(Device):
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 274, in __new__
    new_class.add_to_class(field.name, new_field)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related.py", line 700, in contribute_to_class
    super(ForeignObject, self).contribute_to_class(cls, name, private_only=private_only, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related.py", line 314, in contribute_to_class
    lazy_related_operation(resolve_related_class, cls, self.remote_field.model, field=self)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related.py", line 81, in lazy_related_operation
    return apps.lazy_model_operation(partial(function, **kwargs), *model_keys)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/fields/related.py", line 79, in <genexpr>
    model_keys = (make_model_tuple(m) for m in models)
  File "/usr/local/lib/python3.5/site-packages/django/db/models/utils.py", line 23, in make_model_tuple
    "must be of the form 'app_label.ModelName'." % model
ValueError: Invalid model reference 'core.models.User'. String model references must be of the form 'app_label.ModelName'.
```
My user model class is in the `/path/to/project/core/models.py`, so the reference has to be `core.models.User`.

Besides, I set the `USER_MODEL` to be `core.User` for passing the above check, but the table create syntax in database is still the default value of `USER_MODEL`(`auth_user`): (take `push_notifications_apnsdevice` as example)
```
CREATE TABLE `push_notifications_apnsdevice` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `active` tinyint(1) NOT NULL,
  `date_created` datetime DEFAULT NULL,
  `device_id` char(32) DEFAULT NULL,
  `registration_id` varchar(200) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `registration_id` (`registration_id`),
  KEY `push_notifications_apnsdevice_user_id_44cc44d2_fk_auth_user_id` (`user_id`),
  KEY `push_notifications_apnsdevice_9379346c` (`device_id`),
  CONSTRAINT `push_notifications_apnsdevice_user_id_44cc44d2_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by jleclanche** [comment]
`core.User` is correct. Django will pick up on it correctly. I don't know why the migration wouldn't use the correct table.

**Comment by jleclanche** [comment]
Also you probably want to change your mysql default charset to utf-8 (or better yet, switch to Postgres 😉)

**Comment by Malthael** [comment]
I solve it!!! Thank you :)

It needs to make migration and migrate after change the `USER_MODEL`.

**Comment by jleclanche** [comment]
Good to hear! Do consider postgresql :)
