### ISSUE TITLE
'function' object has no attribute 'create_connection'

### ISSUE THREAD

**Issue by lengzuo** [jleclanche/django-push-notifications#423]

**Comment by lengzuo** [comment]
Hello all,

I running into an issue when using this library.
```javascript
>>> str = "You've have a email".encode('utf-8')
>>> str
"You've have a email"
>>> from push_notifications.models import APNSDevice
>>> device = APNSDevice.objects.get(id=1)
>>> device.send_message(str)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/push_notifications/models.py", line 159, in send_message
    **kwargs
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/push_notifications/apns.py", line 113, in apns_send_message
    certfile=certfile, **kwargs
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/push_notifications/apns.py", line 66, in _apns_send
    client = _apns_create_socket(certfile=certfile, application_id=application_id)
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/push_notifications/apns.py", line 38, in _apns_create_socket
    use_alternative_port=get_manager().get_apns_use_alternative_port(application_id)
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/apns2/client.py", line 39, in __init__
    self._init_connection(use_sandbox, use_alternative_port, proto)
  File "/Users/zuo/Desktop/minihouse/env/lib/python2.7/site-packages/apns2/client.py", line 48, in _init_connection
    self._connection = self.__credentials.create_connection(server, port,
AttributeError: 'function' object has no attribute 'create_connection'
```
